image:
  # Use "ghcr.io/berriai/litellm-database" for optimized image with database
  repository: ghcr.io/berriai/litellm-non_root
  pullPolicy: IfNotPresent
  # Overrides the image tag whose default is the chart appVersion.
  tag: main-v1.74.0-stable@sha256:9dd6930315006fcfd7b77950a6063ca62c2f8f0e4a487b89ae010661bc838a5c
