image:
  # Use "ghcr.io/berriai/litellm-database" for optimized image with database
  repository: ghcr.io/berriai/litellm-non_root
  pullPolicy: IfNotPresent
  # Overrides the image tag whose default is the chart appVersion.
  tag: main-v1.74.3-stable@sha256:f644d9f60dcffba407dd42f2e07d676dfb0e3383806295666b8240a0a87ecfa4
